export const FETCH_SONGS = "FETCH_SONGS";
export const FETCH_SONGS_SUCCESS = "FETCH_SONGS_SUCCESS";
export const FETCH_SONGS_ERROR = "FETCH_SONGS_ERROR";
export const FETCH_SONG_ERROR = "FETCH_SONGS_ERROR";

export const SONG_SORT_BY_ELEMENT = "SONG_SORT_BY_ELEMENT";

export const FILTER_ALBUM = "FILTER_BY_ALBUM";
